push lab3
DDemagoGG/OS-labs-2023 pull request #5
Opened 2023-11-01 20:44 UTC by DDemagoGG

2023-11-02 12:13 UTC, QElderDelta requested changes

2023-11-02 12:13 UTC, QElderDelta commented on lab3/src/parent.cpp
> +int fork_process(){
Мне кажется, что лучше макрос сделать и в него все вызовы засовывать, чем на каждый системный вызов такую обретку писать. Пример тут https://man7.org/linux/man-pages/man2/mmap.2.html, макрос handle_error в конце, где пример кода

2023-11-02 12:13 UTC, QElderDelta commented on tests/lab3_test.cpp
> +    ASSERT_EQ(check("1 2 3"), 6);
EXPECT_

2023-11-02 12:13 UTC, QElderDelta commented on tests/lab3_test.cpp
> +    f.open("test");
```std::fstream f("test");```

2023-11-02 12:13 UTC, QElderDelta commented on tests/lab3_test.cpp
> +    f.open("test");
По-хорошему надо создавать файл, который в конце исполнения теста удалится

2023-11-02 12:13 UTC, QElderDelta commented on lab3/src/parent.cpp
> +// #include <iostream>
Убрать закомментированное

2023-11-02 12:13 UTC, QElderDelta commented on lab3/src/parent.cpp
> +std::string isValidInput(std::istream &input){
Функция называется isValidInput, а возвращает std::string. Выглядит нелогично, надо либо название поменять, либо возвращаемый тип

2023-11-02 12:13 UTC, QElderDelta commented on lab3/src/parent.cpp
> +        int * ptr = (int *)create_MMF(nullptr, sizeof(int) * 2, PROT_WRITE, MAP_SHARED, fd, 0);
Не вижу munmap

2023-11-04 06:31 UTC, DDemagoGG commented on tests/lab3_test.cpp
> +    ASSERT_EQ(check("1 2 3"), 6);
Исправлено

2023-11-04 06:46 UTC, DDemagoGG commented on tests/lab3_test.cpp
> +    f.open("test");
Исправлено

2023-11-04 06:47 UTC, DDemagoGG commented on lab3/src/parent.cpp
> +// #include <iostream>
Исправлено

2023-11-04 06:51 UTC, DDemagoGG commented on lab3/src/parent.cpp
> +std::string isValidInput(std::istream &input){
исправлено

2023-11-04 06:57 UTC, DDemagoGG commented on lab3/src/parent.cpp
> +        int * ptr = (int *)create_MMF(nullptr, sizeof(int) * 2, PROT_WRITE, MAP_SHARED, fd, 0);
исправлено

2023-11-04 07:05 UTC, DDemagoGG commented on lab3/src/parent.cpp
> +int fork_process(){
Забил и ничего не делаю

2023-11-04 07:09 UTC, merged