complete lab5
DDemagoGG/OS-labs-2023 pull request #7
Opened 2023-12-17 12:37 UTC by DDemagoGG

2023-12-18 20:11 UTC, QElderDelta requested changes

2023-12-18 20:11 UTC, QElderDelta commented on lab5/CMakeLists.txt
> +# add_dependencies(lab5 computer)
Закомментированный код выпили

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/computer.hpp
> +#include "socket.hpp"
Я не вкурил, зачем отдельные хэдера?

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/socket.hpp
> +const int PORT_BASE = 4000;
constexpr

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/socket.hpp
> +    sucsess,
success

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/socket.cpp
> +Msg::Msg() : action(noAction), arg1(0), arg2(0) {}
Лучше в классе поля сразу проинициализируй, а этот конструктор убери

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/tree.hpp
> +    int upToRootChild(Tree * root){
Вынеси определения этих функций так же в .cpp, зачем они здесь?

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/socket.cpp
> +    zmq_msg_init_data(&input, m, sizeof(Msg), NULL, NULL);
nullptr

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/socket.cpp
> +    zmq_msg_t input;
Есть же нормальная плюсовая обертка у zmq, я у твоих коллег видел. Чем обоснован выбор сишной, неужели в кайф вот с этими init'ами и прочим развлекаться

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/socket.cpp
> +    m = *static_cast<Msg *>(zmq_msg_data(&output));
Может это после проверки res делать, чтобы не портить m в случае неуспеха?

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/manager.cpp
> +				new_socket = new BindingSocket(child_id);
Не увидел где эта память освобождается, у тебя утечка

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/manager.cpp
> +					return 0;
Ну явно не ноль здесь должен быть. Код после exec'a выполняется только в случае проблем

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/manager.cpp
> +				} else{
Ну сделай пробельчик между else и {

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/socket.hpp
> +    int sendNoWaitRecvMsg(Msg * input, Msg & output);
Я чет не вкурил какой смысл иметь и sendRecvMsg, и sendNoWaitRecvMsg, если в обоих случаях энивей синхронизация на моменте recv

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/computer.cpp
> +						children.erase(child_id);
Вложенность адовая

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/computer.cpp
> +						children.erase(child_id);
Самый простой вариант уменьшить - под каждый из обрабатываемых ActionType сделать функцию, куда вынести код

2023-12-18 20:11 UTC, QElderDelta commented on lab5/include/socket.hpp
> +enum ActionType{
Ты специально пробельчики перед { не ставишь?

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/computer.cpp
> +				new_socket = new BindingSocket(child_id);
Та же самая ситуация с утечкой

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/computer.cpp
> +				if (local_map.find(key) != local_map.end()){
Шоб 2 раза в мапу не ходить можно использовать if с инициализацией:
```cpp
if (auto it = local_map.find(key); it != local_map.end()) {
  std::cout << it->second << std::endl;
}
```

2023-12-18 20:11 UTC, QElderDelta commented on lab5/src/computer.cpp
> +				sleep(1);
Вот это признак, что что-то не так. Жду пояснений зачем он здесь

2023-12-19 16:11 UTC, DDemagoGG commented on lab5/CMakeLists.txt
> +# add_dependencies(lab5 computer)
Исправил

2023-12-19 16:11 UTC, DDemagoGG commented on lab5/include/computer.hpp
> +#include "socket.hpp"
Для кайфа

2023-12-19 16:13 UTC, DDemagoGG commented on lab5/include/socket.hpp
> +const int PORT_BASE = 4000;
Исправлено

2023-12-19 16:14 UTC, DDemagoGG commented on lab5/include/socket.hpp
> +    sucsess,
Исправлено

2023-12-19 16:19 UTC, DDemagoGG commented on lab5/src/socket.cpp
> +Msg::Msg() : action(noAction), arg1(0), arg2(0) {}
Исправлено

2023-12-19 16:23 UTC, DDemagoGG commented on lab5/src/socket.cpp
> +    zmq_msg_init_data(&input, m, sizeof(Msg), NULL, NULL);
Исправлено

2023-12-19 16:28 UTC, DDemagoGG commented on lab5/src/socket.cpp
> +    zmq_msg_t input;
Я думал, надо делать с сишной (мы же почему-то во 2 лабе не могли использовать std::threads) + впадлу было возиться с установкой спп библиотеки, мне хватило мороки на сишной

2023-12-19 16:30 UTC, DDemagoGG commented on lab5/include/tree.hpp
> +    int upToRootChild(Tree * root){
Исправлено

2023-12-19 16:31 UTC, DDemagoGG commented on lab5/src/socket.cpp
> +    m = *static_cast<Msg *>(zmq_msg_data(&output));
Исправлено

2023-12-19 16:49 UTC, DDemagoGG commented on lab5/src/manager.cpp
> +				new_socket = new BindingSocket(child_id);
Исправлено

2023-12-19 16:50 UTC, DDemagoGG commented on lab5/src/manager.cpp
> +					return 0;
Исправлено

2023-12-19 16:50 UTC, DDemagoGG commented on lab5/src/manager.cpp
> +				} else{
это мой style

2023-12-19 21:06 UTC, DDemagoGG commented on lab5/src/computer.cpp
> +				sleep(1);
Исправлено

2023-12-19 21:07 UTC, merged